name: fikraa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  icons_plus: ^4.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.5.7
  http: ^1.2.2
  fl_chart: ^0.69.0
  syncfusion_flutter_gauges: ^21.2.3
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.7.15
  cloud_functions: ^4.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Ajoutez la dépendance flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:  # Configuration pour l'icône de l'application
  android: true
  ios: true
  image_path: "images/banner.png"  # Spécifiez le chemin de votre logo
